name: Urvaseo
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.3
  sqflite: ^2.0.0+3
  dio: ^4.0.0
  cupertino_icons: ^1.0.2
  chewie: ^1.2.2
  video_player: ^2.5.3
  flutter_local_notifications: ^9.1.7
  flutter_bloc: ^7.0.0
  shared_preferences: ^2.0.10
  cached_network_image: ^3.0.0
  provider: ^6.1.1
  path_provider: ^2.0.2
  image_gallery_saver: '^2.0.3'
  url_launcher: ^6.0.9




dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/WEBSISAPP.png
    - assets/Urvaseo.png

